version: '2'
services:
  app:
    container_name: sysmondash-app
    image: nuxsmin/docker-sysmondash
    restart: always
    ports:
      - "80:80"
    environment:
      - SMD_UID=9001
      - SMD_BRANCH=master
